#!/bin/bash
SECONDS=0
echo Enter username or domain name         #Input
read username
ui $username | grep "Doc Root" | cut -d":" -f2 > docrot.txt
isuser=$( cat docrot.txt | wc -l )
if [ "$isuser" -eq 0 ];                                                           #if [ -f "$mytext3" ];
then
echo "The entered username or domain name is incorrect"
fi
echo "Checking for common malicious files for $username in all backup"
echo -e " \n"
echo "#######################################################################################"
var=$( cat docrot.txt )
docurt="${var%/public_html*}"
mytext2="${var%public_html*}malware.txt"
echo $mytext2 > ding.txt
mytext3=$( cat ding.txt )
mytext4=$( cat $mytext3 | grep $username | wc -l )
rm -f /root/nex3.txt 2> /dev/null
rm -f /root/docrot.txt 2> /dev/null
rm -f /root/ding.txt 2> /dev/null
rm -f /root/nex4.txt 2> /dev/null
rm -f /root/present.txt 2> /dev/null
rm -f $docurt/malware_new.txt 2> /dev/null
rm -f $docurt/malware_new2.txt 2> /dev/null
if [ "$mytext4" -gt 300 ];
then
echo "$mytext3 file exist and has more than 300 malicious files in it. So exiting"
return
fi
if [ "$mytext4" -gt 0 ];                                                           #if [ -f "$mytext3" ];
then
echo "$mytext3 file exist and has $mytext4 malware files"
echo -e " \n"
echo "#######################################################################################"
cat $mytext2 | awk '{ print $1 }' >> $docurt/malware_new.txt
rev $docurt/malware_new.txt | cut -c2- |rev >> $docurt/malware_new2.txt
for file in $(cat $docurt/malware_new2.txt);
do
mytext="$file"
echo ${mytext#*$username/} >> nex3.txt
done
rm -f datesop.txt
sshrestore --list -u $username | grep $username | grep -v seed | cut -f1 -d":" >> datesop.txt
for file in $(cat datesop.txt);
do
daypath="$file/homedir/"
echo $daypath
cd $daypath
for file in $(cat /root/nex3.txt);
do
ll $file 2>/dev/null >> /root/present.txt
done
cat /root/present.txt
rm -f /root/present.txt 2> /dev/null
echo -e " \n"
echo "#######################################################################################"
done
cd
else
echo "$mytext3 does not exist or there is no malware files specified in $mytext3 file"
fi
duration=$SECONDS
red=`tput setaf 1`
green=`tput setaf 2`
reset=$(tput sgr0)
echo "The script took${green} $(($duration / 60)) minutes and $(($duration % 60)) seconds ${reset} to check the presence of $mytext4 infected file in backup"

echo "#######################################################################################"

echo "${red}Note: The script only checks if the files listed in malware.txt. So a infected file which is not listed in malware.txt will not be detected by the script${reset}"
echo -e "\e[3;4;33m${red}It is always recommended to inform the customer to get their website code checked with a professional website security expert as the same vulnerabilities that were exploited to hack the website might be present in the backup.${reset}\n\e[0m"
echo "#######################################################################################"
